baseURL = "https://newdegeneration.xyz/"
languageCode = 'en-us'

[params.documents.portfolio_pdf]
en = "/portfolio-en.pdf"
bg = "/portfolio-bg.pdf"

[params.documents.cv_pdf]
en = "/cv-en.pdf"
bg = "/cv-bg.pdf"

[params.social]
    email     = "mailto:av0id.biz@gmail.com"
    instagram = "https://www.instagram.com/avoid.nd/"
    facebook  = "https://www.facebook.com/av0id.nd/"
    youtube   = "https://www.youtube.com/@newdegeneration"

params_sameas_other = [
        "https://twitter.com/new_degen",
        "https://www.youtube.com/@newdegeneration",
        "https://www.wikidata.org/wiki/Q124417026",
        "https://www.goodreads.com/author/show/48653203",
        "https://www.imdb.com/name/nm16814810",
        "https://sussex.academia.edu/NikolaStoyanov"
]

[sitemap]
  filename = "sitemap.xml"
  enableRobotsTXT = true
  changeFreq = "daily"
  image = true

[markup]
  defaultMarkdownHandler = 'goldmark'

[taxonomies]
  category = "categories"

[minify]
  disableXML = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    disabled = false
    title = "Nikola Stoyanov"
    weight = "1"
    [languages.en.params]
      Description = "Nikola Stoyanov is a visual artist and machine philosopher hailing from Varna, Bulgaria. His work aims to traverse the boundary between research-based and speculative practices. Area of interest include the intersection of infrastructure, technological apparatus, art, and everyday life, intertwining the humanities with scientific methodologies."
      name = "Nikola Stoyanov"
      alternateName = "Nikola Vladislavov Stoyanov"
      jobTitle = "Artist and philosopher"
      profileImage = "images/profile.jpg"
      organizerUrl = "https://newdegeneration.xyz/bio/"

  [languages.bg]
    languageName = "Български"
    disabled = false
    weight = "2"
    title = "Никола Стоянов"
    [languages.bg.params]
      Description = "Никола Стоянов е визуален артист и машинен философ от Варна, България, който се занимава с пресичането между изследователските и спекулативните практики. Работата му обхваща теми като хаос, киберготика и акселерационистка философия, като се фокусира върху пресичането на инфраструктурата, технологичния апарат, изкуството и ежедневието."
      name = "Никола Стоянов"
      alternateName = "Никола Владиславов Стоянов"
      jobTitle = "Aртист и философ"
      profileImage = "images/profile.jpg"
      organizerUrl = "https://newdegeneration.xyz/bio/"

